
#配置mybatis
mybatis:
  type-aliases-package: come.example.demo
  mapper-locations: classpath:mapper/*Mapper.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource


